name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt || echo "No requirements.txt file"

    - name: Run Python script
      run: |
        source venv/bin/activate
        python main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-script
        path: main.py
